In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 =  {
    "Name": ['Haseeb', 'Ibrar', 'Ahmad', 'Ali'],
    "Marks": [67, 60, 55, 50],
    "City": [ 'Islamabad', 'Rawalpindi', 'Abbottabad', 'D.I.Khan']
}

In [3]:
df=pd.DataFrame(dict1)

In [4]:
df

     Name  Marks        City
0  Haseeb     67   Islamabad
1   Ibrar     60  Rawalpindi
2   Ahmad     55  Abbottabad
3     Ali     50    D.I.Khan

In [5]:
df.to_csv('Friends.csv')

In [6]:
df.to_csv('Friends_indexFalse.csv', index=False)

In [7]:
df.head(2)

     Name  Marks        City
0  Haseeb     67   Islamabad
1   Ibrar     60  Rawalpindi

In [8]:
df.tail(2)

    Name  Marks        City
2  Ahmad     55  Abbottabad
3    Ali     50    D.I.Khan

In [9]:
df.describe()

          Marks
count   4.00000
mean   58.00000
std     7.25718
min    50.00000
25%    53.75000
50%    57.50000
75%    61.75000
max    67.00000

In [10]:
Cars = pd.read_csv('Cars.csv')

In [11]:
Cars

   Car No.  Speed        City
0      101    120   Islamabad
1      102    110  Rawalpindi
2      103    100  Abbottabad
3      104     90    D.I.Khan

In [12]:
Cars.index= ['First', 'Second', 'Third', 'Forth']

In [13]:
Cars

        Car No.  Speed        City
First       101    120   Islamabad
Second      102    110  Rawalpindi
Third       103    100  Abbottabad
Forth       104     90    D.I.Khan

In [14]:
ser= pd.Series (np.random.rand(34))

In [15]:
ser

0     0.456970
1     0.674450
2     0.291743
3     0.575930
4     0.053862
5     0.302991
6     0.063142
7     0.993981
8     0.480647
9     0.850619
10    0.849694
11    0.680471
12    0.887999
13    0.950849
14    0.783393
15    0.419395
16    0.098559
17    0.516039
18    0.185354
19    0.587945
20    0.550942
21    0.392833
22    0.544059
23    0.757285
24    0.531507
25    0.950378
26    0.493057
27    0.853453
28    0.628905
29    0.662868
30    0.675526
31    0.808184
32    0.616800
33    0.590038
dtype: float64

In [16]:
type (ser)

pandas.Series

In [17]:
newdf = pd.DataFrame(np.random.rand(334,5), index= np.arange (334))

In [18]:
newdf

            0         1         2         3         4
0    0.224392  0.258515  0.242747  0.519506  0.295264
1    0.247981  0.612985  0.511337  0.343000  0.376724
2    0.397843  0.585511  0.956491  0.707956  0.384091
3    0.451692  0.002539  0.882604  0.583532  0.909673
4    0.223443  0.668205  0.889958  0.461566  0.554100
..        ...       ...       ...       ...       ...
329  0.264761  0.503505  0.617920  0.521972  0.682148
330  0.923592  0.787748  0.944127  0.992308  0.630256
331  0.003740  0.121006  0.055026  0.777254  0.913972
332  0.472209  0.769249  0.315024  0.413983  0.513882
333  0.817662  0.286958  0.842214  0.165451  0.318849

[334 rows x 5 columns]

In [19]:
type(newdf)

pandas.DataFrame

In [20]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.483996    0.494247    0.497343    0.502048    0.502256
std      0.307285    0.290048    0.282529    0.300888    0.284951
min      0.001439    0.002539    0.005324    0.001009    0.001697
25%      0.214881    0.233214    0.249137    0.223031    0.265539
50%      0.458909    0.503810    0.503610    0.495424    0.494424
75%      0.776121    0.740310    0.761164    0.768619    0.766590
max      0.999268    0.999955    0.999732    0.999162    0.999520

In [21]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [28]:
newdf[[0][0]]= 'Haseeb'

In [29]:
newdf.head()

        0         1         2         3         4
0  Haseeb  0.258515  0.242747  0.519506  0.295264
1  Haseeb  0.612985  0.511337  0.343000  0.376724
2  Haseeb  0.585511  0.956491  0.707956  0.384091
3  Haseeb  0.002539  0.882604  0.583532  0.909673
4  Haseeb  0.668205  0.889958  0.461566  0.554100

In [30]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [31]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [32]:
newdf [[0][0]]= 0.3

In [33]:
newdf.head()

     0         1         2         3         4
0  0.3  0.258515  0.242747  0.519506  0.295264
1  0.3  0.612985  0.511337  0.343000  0.376724
2  0.3  0.585511  0.956491  0.707956  0.384091
3  0.3  0.002539  0.882604  0.583532  0.909673
4  0.3  0.668205  0.889958  0.461566  0.554100

In [34]:
newdf.to_numpy

<bound method DataFrame.to_numpy of        0         1         2         3         4
0    0.3  0.258515  0.242747  0.519506  0.295264
1    0.3  0.612985  0.511337  0.343000  0.376724
2    0.3  0.585511  0.956491  0.707956  0.384091
3    0.3  0.002539  0.882604  0.583532  0.909673
4    0.3  0.668205  0.889958  0.461566  0.554100
..   ...       ...       ...       ...       ...
329  0.3  0.503505  0.617920  0.521972  0.682148
330  0.3  0.787748  0.944127  0.992308  0.630256
331  0.3  0.121006  0.055026  0.777254  0.913972
332  0.3  0.769249  0.315024  0.413983  0.513882
333  0.3  0.286958  0.842214  0.165451  0.318849

[334 rows x 5 columns]>

In [35]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,...,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000
1,0.258515,0.612985,0.585511,0.002539,0.668205,0.614908,0.371477,0.755164,0.913206,0.804895,...,0.271899,0.669776,0.124874,0.489863,0.567004,0.503505,0.787748,0.121006,0.769249,0.286958
2,0.242747,0.511337,0.956491,0.882604,0.889958,0.672696,0.695735,0.958470,0.395738,0.175974,...,0.793304,0.032215,0.598179,0.986208,0.458480,0.617920,0.944127,0.055026,0.315024,0.842214
3,0.519506,0.343000,0.707956,0.583532,0.461566,0.310397,0.300988,0.672938,0.808001,0.257902,...,0.182681,0.666754,0.259408,0.752957,0.010110,0.521972,0.992308,0.777254,0.413983,0.165451
4,0.295264,0.376724,0.384091,0.909673,0.554100,0.078933,0.925078,0.138493,0.694774,0.810627,...,0.143889,0.821277,0.650988,0.219601,0.769348,0.682148,0.630256,0.913972,0.513882,0.318849

In [36]:
newdf.sort_index(axis=0, ascending= False)

       0         1         2         3         4
333  0.3  0.286958  0.842214  0.165451  0.318849
332  0.3  0.769249  0.315024  0.413983  0.513882
331  0.3  0.121006  0.055026  0.777254  0.913972
330  0.3  0.787748  0.944127  0.992308  0.630256
329  0.3  0.503505  0.617920  0.521972  0.682148
..   ...       ...       ...       ...       ...
4    0.3  0.668205  0.889958  0.461566  0.554100
3    0.3  0.002539  0.882604  0.583532  0.909673
2    0.3  0.585511  0.956491  0.707956  0.384091
1    0.3  0.612985  0.511337  0.343000  0.376724
0    0.3  0.258515  0.242747  0.519506  0.295264

[334 rows x 5 columns]

In [37]:
newdf.sort_index(axis=1, ascending=False)

            4         3         2         1    0
0    0.295264  0.519506  0.242747  0.258515  0.3
1    0.376724  0.343000  0.511337  0.612985  0.3
2    0.384091  0.707956  0.956491  0.585511  0.3
3    0.909673  0.583532  0.882604  0.002539  0.3
4    0.554100  0.461566  0.889958  0.668205  0.3
..        ...       ...       ...       ...  ...
329  0.682148  0.521972  0.617920  0.503505  0.3
330  0.630256  0.992308  0.944127  0.787748  0.3
331  0.913972  0.777254  0.055026  0.121006  0.3
332  0.513882  0.413983  0.315024  0.769249  0.3
333  0.318849  0.165451  0.842214  0.286958  0.3

[334 rows x 5 columns]

In [38]:
newdf.head()

     0         1         2         3         4
0  0.3  0.258515  0.242747  0.519506  0.295264
1  0.3  0.612985  0.511337  0.343000  0.376724
2  0.3  0.585511  0.956491  0.707956  0.384091
3  0.3  0.002539  0.882604  0.583532  0.909673
4  0.3  0.668205  0.889958  0.461566  0.554100

In [39]:
newdf[0]

0      0.3
1      0.3
2      0.3
3      0.3
4      0.3
      ...
329    0.3
330    0.3
331    0.3
332    0.3
333    0.3
Name: 0, Length: 334, dtype: float64

In [40]:
type(newdf[0])

pandas.Series

In [41]:
newdf2 = newdf.copy()

In [42]:
newdf2 [[0][0]]= 666777

In [87]:
newdf2.head()

        0         1         2         3         4
0  666777  0.258515  0.242747  0.519506  0.295264
1  666777  0.612985  0.511337  0.343000  0.376724
2  666777  0.585511  0.956491  0.707956  0.384091
3  666777  0.002539  0.882604  0.583532  0.909673
4  666777  0.668205  0.889958  0.461566  0.554100

In [96]:
newdf.iloc[0,0]=123

In [94]:
newdf

         A     B         C         D         E       0
0    123.0  56.0  0.242747  0.519506  0.295264  Haseeb
1      0.3  56.0  0.956491  0.707956  0.384091     NaN
2      0.3  56.0  0.882604  0.583532  0.909673     NaN
3      0.3  56.0  0.889958  0.461566  0.554100     NaN
4      0.3  56.0  0.695735  0.300988  0.925078     NaN
..     ...   ...       ...       ...       ...     ...
327    0.3  56.0  0.617920  0.521972  0.682148     NaN
328    0.3  56.0  0.944127  0.992308  0.630256     NaN
329    0.3  56.0  0.055026  0.777254  0.913972     NaN
330    0.3  56.0  0.315024  0.413983  0.513882     NaN
331    0.3  56.0  0.842214  0.165451  0.318849     NaN

[332 rows x 6 columns]

In [46]:
newdf.columns=list("ABCDE")

In [47]:
newdf.head()

       A         B         C         D         E
0  123.0  0.258515  0.242747  0.519506  0.295264
1    0.3  0.612985  0.511337  0.343000  0.376724
2    0.3  0.585511  0.956491  0.707956  0.384091
3    0.3  0.002539  0.882604  0.583532  0.909673
4    0.3  0.668205  0.889958  0.461566  0.554100

In [48]:
newdf.loc[0,'A'] = 12345

In [49]:
newdf.head()

         A         B         C         D         E
0  12345.0  0.258515  0.242747  0.519506  0.295264
1      0.3  0.612985  0.511337  0.343000  0.376724
2      0.3  0.585511  0.956491  0.707956  0.384091
3      0.3  0.002539  0.882604  0.583532  0.909673
4      0.3  0.668205  0.889958  0.461566  0.554100

In [50]:
newdf.loc[0,0]= 99

In [51]:
newdf.head()

         A         B         C         D         E     0
0  12345.0  0.258515  0.242747  0.519506  0.295264  99.0
1      0.3  0.612985  0.511337  0.343000  0.376724   NaN
2      0.3  0.585511  0.956491  0.707956  0.384091   NaN
3      0.3  0.002539  0.882604  0.583532  0.909673   NaN
4      0.3  0.668205  0.889958  0.461566  0.554100   NaN

In [52]:
newdf.drop(0,axis=1)

           A         B         C         D         E
0    12345.0  0.258515  0.242747  0.519506  0.295264
1        0.3  0.612985  0.511337  0.343000  0.376724
2        0.3  0.585511  0.956491  0.707956  0.384091
3        0.3  0.002539  0.882604  0.583532  0.909673
4        0.3  0.668205  0.889958  0.461566  0.554100
..       ...       ...       ...       ...       ...
329      0.3  0.503505  0.617920  0.521972  0.682148
330      0.3  0.787748  0.944127  0.992308  0.630256
331      0.3  0.121006  0.055026  0.777254  0.913972
332      0.3  0.769249  0.315024  0.413983  0.513882
333      0.3  0.286958  0.842214  0.165451  0.318849

[334 rows x 5 columns]

In [53]:
newdf.loc[0,'A'] = 100

In [54]:
newdf.head()

       A         B         C         D         E     0
0  100.0  0.258515  0.242747  0.519506  0.295264  99.0
1    0.3  0.612985  0.511337  0.343000  0.376724   NaN
2    0.3  0.585511  0.956491  0.707956  0.384091   NaN
3    0.3  0.002539  0.882604  0.583532  0.909673   NaN
4    0.3  0.668205  0.889958  0.461566  0.554100   NaN

In [55]:
newdf= newdf.drop(0,axis=1)

In [97]:
newdf.head()

       A     B         C         D         E       0
0  123.0  56.0  0.242747  0.519506  0.295264  Haseeb
1    0.3  56.0  0.956491  0.707956  0.384091     NaN
2    0.3  56.0  0.882604  0.583532  0.909673     NaN
3    0.3  56.0  0.889958  0.461566  0.554100     NaN
4    0.3  56.0  0.695735  0.300988  0.925078     NaN

In [56]:
newdf.loc [[1,2], ['A','C']]

     A         C
1  0.3  0.511337
2  0.3  0.956491

In [57]:
newdf.loc [[1,2], :]

     A         B         C         D         E
1  0.3  0.612985  0.511337  0.343000  0.376724
2  0.3  0.585511  0.956491  0.707956  0.384091

In [58]:
newdf

         A         B         C         D         E
0    100.0  0.258515  0.242747  0.519506  0.295264
1      0.3  0.612985  0.511337  0.343000  0.376724
2      0.3  0.585511  0.956491  0.707956  0.384091
3      0.3  0.002539  0.882604  0.583532  0.909673
4      0.3  0.668205  0.889958  0.461566  0.554100
..     ...       ...       ...       ...       ...
329    0.3  0.503505  0.617920  0.521972  0.682148
330    0.3  0.787748  0.944127  0.992308  0.630256
331    0.3  0.121006  0.055026  0.777254  0.913972
332    0.3  0.769249  0.315024  0.413983  0.513882
333    0.3  0.286958  0.842214  0.165451  0.318849

[334 rows x 5 columns]

In [59]:
newdf.loc [(newdf['B']<0.3)]

         A         B         C         D         E
0    100.0  0.258515  0.242747  0.519506  0.295264
3      0.3  0.002539  0.882604  0.583532  0.909673
12     0.3  0.266960  0.840325  0.192950  0.752088
15     0.3  0.276648  0.523923  0.219951  0.062956
17     0.3  0.100084  0.472459  0.705641  0.514858
..     ...       ...       ...       ...       ...
319    0.3  0.042609  0.656942  0.153777  0.283356
324    0.3  0.271899  0.793304  0.182681  0.143889
326    0.3  0.124874  0.598179  0.259408  0.650988
331    0.3  0.121006  0.055026  0.777254  0.913972
333    0.3  0.286958  0.842214  0.165451  0.318849

[106 rows x 5 columns]

In [60]:
newdf.loc [(newdf['B']<0.3) & (newdf['C']>0.1)]

         A         B         C         D         E
0    100.0  0.258515  0.242747  0.519506  0.295264
3      0.3  0.002539  0.882604  0.583532  0.909673
12     0.3  0.266960  0.840325  0.192950  0.752088
15     0.3  0.276648  0.523923  0.219951  0.062956
17     0.3  0.100084  0.472459  0.705641  0.514858
..     ...       ...       ...       ...       ...
318    0.3  0.095835  0.610071  0.024236  0.480224
319    0.3  0.042609  0.656942  0.153777  0.283356
324    0.3  0.271899  0.793304  0.182681  0.143889
326    0.3  0.124874  0.598179  0.259408  0.650988
333    0.3  0.286958  0.842214  0.165451  0.318849

[95 rows x 5 columns]

In [61]:
newdf.head()

       A         B         C         D         E
0  100.0  0.258515  0.242747  0.519506  0.295264
1    0.3  0.612985  0.511337  0.343000  0.376724
2    0.3  0.585511  0.956491  0.707956  0.384091
3    0.3  0.002539  0.882604  0.583532  0.909673
4    0.3  0.668205  0.889958  0.461566  0.554100

In [62]:
newdf.iloc [0,4]

np.float64(0.2952637534848229)

In [63]:
newdf.iloc[[1,2] , [3,4]]

          D         E
1  0.343000  0.376724
2  0.707956  0.384091

In [64]:
newdf.drop(['A', 'C'], axis = 1)

            B         D         E
0    0.258515  0.519506  0.295264
1    0.612985  0.343000  0.376724
2    0.585511  0.707956  0.384091
3    0.002539  0.583532  0.909673
4    0.668205  0.461566  0.554100
..        ...       ...       ...
329  0.503505  0.521972  0.682148
330  0.787748  0.992308  0.630256
331  0.121006  0.777254  0.913972
332  0.769249  0.413983  0.513882
333  0.286958  0.165451  0.318849

[334 rows x 3 columns]

In [65]:
newdf.drop([1, 5],inplace = True)

In [66]:
newdf

         A         B         C         D         E
0    100.0  0.258515  0.242747  0.519506  0.295264
2      0.3  0.585511  0.956491  0.707956  0.384091
3      0.3  0.002539  0.882604  0.583532  0.909673
4      0.3  0.668205  0.889958  0.461566  0.554100
6      0.3  0.371477  0.695735  0.300988  0.925078
..     ...       ...       ...       ...       ...
329    0.3  0.503505  0.617920  0.521972  0.682148
330    0.3  0.787748  0.944127  0.992308  0.630256
331    0.3  0.121006  0.055026  0.777254  0.913972
332    0.3  0.769249  0.315024  0.413983  0.513882
333    0.3  0.286958  0.842214  0.165451  0.318849

[332 rows x 5 columns]

In [67]:
newdf.reset_index(drop=True, inplace =True)

In [68]:
newdf.head()

       A         B         C         D         E
0  100.0  0.258515  0.242747  0.519506  0.295264
1    0.3  0.585511  0.956491  0.707956  0.384091
2    0.3  0.002539  0.882604  0.583532  0.909673
3    0.3  0.668205  0.889958  0.461566  0.554100
4    0.3  0.371477  0.695735  0.300988  0.925078

In [69]:
newdf.loc[:,['B']] = 56

In [98]:
newdf.head()

       A     B         C         D         E       0
0  123.0  56.0  0.242747  0.519506  0.295264  Haseeb
1    0.3  56.0  0.956491  0.707956  0.384091     NaN
2    0.3  56.0  0.882604  0.583532  0.909673     NaN
3    0.3  56.0  0.889958  0.461566  0.554100     NaN
4    0.3  56.0  0.695735  0.300988  0.925078     NaN

In [70]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

In [71]:
df = pd.DataFrame(
         {"name": ["Alfred", "Batman", "Alfred"],
         "toy": [np.nan, "Batmobile", "Bullwhip"],
         "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]})

In [72]:
df

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [73]:
df.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [74]:
df

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [75]:
df.drop_duplicates(subset=['name'], keep='first')

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25

In [76]:
df.drop_duplicates(subset=['name'], keep='last')

     name        toy       born
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [77]:
df['name'].value_counts()

name
Alfred    2
Batman    1
Name: count, dtype: int64

In [78]:
df['toy'].value_counts(dropna=False)

toy
NaN          1
Batmobile    1
Bullwhip     1
Name: count, dtype: int64

In [79]:
df

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [80]:
df.isnull()

    name    toy   born
0  False   True   True
1  False  False  False
2  False  False   True

In [81]:
df.notnull()

   name    toy   born
0  True  False  False
1  True   True   True
2  True   True  False

In [82]:
quiz=pd.DataFrame({ "column1": [1,2,3],
                  "column2": [4,5,3]})

In [83]:
quiz

   column1  column2
0        1        4
1        2        5
2        3        3

In [84]:
data = pd.read_csv('Cars.csv')

In [85]:
data

   Car No.  Speed        City
0      101    120   Islamabad
1      102    110  Rawalpindi
2      103    100  Abbottabad
3      104     90    D.I.Khan